version: "3.4"
services:
  server:
    env_file:
      - ./server/.env
    container_name: repos-checker-backend
    build:
      context: ./server
      target: development
    volumes:
      - ./server/src/index.ts:/usr/app/backend/src/index.ts
    ports:
      - "5000:5000"
  client:
    container_name: repos-checker-frontend
    environment:
      API_HOST: "${API_HOST:-http://server:5000}"
    build:
      context: ./client
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/usr/app/client/src
      - ./client/public:/usr/app/client/public
    links:
      - server
