name: repos-checker-2.0 client deploy
on:
  push:
    paths:
      - ".github/workflows/client.yml"
      - "client/**"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: set account identity
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          EMAIL: ${{ secrets.EMAIL }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config user.name $USER_NAME
          git config user.email $EMAIL
          cd client/
          npm ci
          CI=false npm run build
          git add build/ --force
          git commit -m "Publish"
          git remote add pages https://x-access-token:$ACCESS_TOKEN@github.com/shanwong29/repos-checker-2.0.git
          git push pages HEAD:refs/heads/gh-pages --force
