name: repos-checker client deploy
on:
  push:
    paths:
      - ".github/workflows/client.yml"
      - "client/**"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build the static files
        run: |
          cd client/
          npm ci
          CI=false npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./client/build
